CC 				= g++
CUDAC 			= nvcc
OPTIMUS         = optirun #remover este valor se não estiver em um sistema OPTIMUS (notebook)
CUDA_LIB_PATH   = /usr/local/cuda-5.5/lib64
CUDAFLAGS       = -O3 -arch=sm_21 -m64 -Xcompiler -ftree-vectorize -Xcompiler -msse4 #-I/usr/local/cuda-5.5/extras/CUPTI/include -ccbin g++  -Xcompiler -Wall
CXXFLAGS		= -O3 -w
GENCONDE		= -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=\"sm_35,compute_35\"
OMP_TBB         = -fopenmp -lgomp -ltbb
LIBS			= -Xcompiler -fopenmp -lgomp -ltbb -lpapi -lcuda -I../../lib/ -L../../lib/ga -lga -lm #-L /usr/local/cuda-5.5/extras/CUPTI/lib -L /usr/local/cuda-5.5/extras/CUPTI/lib64 -lcupti
SRC_NAME        = gol
SEQ_SRC_NAME    = gol_seq
BIN_DIR         = ../../bin/

all: clean pskel

seq:  	${SEQ_SRC_NAME}.cpp
	#${CUDAC} ${CXXFLAGS} ${SEQ_SRC_NAME}.cpp -o ${BIN_DIR}${SEQ_SRC_NAME} -Xcompiler ${OMP_TBB}
	#${CUDAC} ${CUDAFLAGS} ${GENCODE} -o ${SEQ_SRC_NAME}.o -c ${SEQ_SRC_NAME}.cpp
	#${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SEQ_SRC_NAME} ${SEQ_SRC_NAME}.o ${LIBS}
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SEQ_SRC_NAME} ${SEQ_SRC_NAME}.cu ${LIBS}

pskel:  ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SRC_NAME} ${SRC_NAME}.cu ${LIBS}

papi:  ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SRC_NAME} ${SRC_NAME}.cu ${LIBS} -DPAPI -DTIME
	
cupti:  ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SRC_NAME} ${SRC_NAME}.cu ${LIBS} -DCUPTI
	
time:  ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SRC_NAME} ${SRC_NAME}.cu ${LIBS} -DTIME
	
pskelv2: ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} ${GENCODE} -o ${SRC_NAME}.o -c ${SRC_NAME}.cu
	${CUDAC} ${CUDAFLAGS} -o ${BIN_DIR}${SRC_NAME} ${SRC_NAME}.o ${LIBS}

testseq:
	time -p ${BIN_DIR}${SEQ_SRC_NAME} 600 600 0
	
testpskel:
	time -p ${BIN_DIR}${SRC_NAME} 1000 1000 9 1.0 32 8 0

testoptimus:
	time -p ${OPTIMUS} ${BIN_DIR}${SRC_NAME} 1000 1000 1 1.0 32 8 0
	
clean:
	 rm -f *.o ${BIN_DIR}${SRC_NAME} ${BIN_DIR}${SEQ_SRC_NAME}
